name: Release

on:
  create:
    tags:
      - "-v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
      - run: python -m pip install --upgrade pip ; poetry-dynamic-versioning
      - run: poetry publish --build --dry-run
