name: Release

on:
  create:
    tags:
      - "-v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade pip
      - run: pip install poetry
      - run: pip install poetry-dynamic-versioning
      - run: dunamai from git --debug
      - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - run: poetry publish --build
